### ISSUE TITLE
Mana Attributes doesnt appear to be working

### ISSUE THREAD

**Issue by Lemenok** [TheRedBrain/manaapi#1]
Hello!

It appears that the mod does not work as expected. I cannot see a mana bar, nor does it appear through the player attribute screen that the player has any Mana set. When checking the config folder for the mod, I also only see a client file, not a server file. It may have been possible that I missed a config, but I checked Spell Engine Extension and all were set true to default to use Mana.

Here is my mod list information.

**Fabric - 1.21.1**

- Azurelib Armor - 2.3.13
- Cloth Config API - 15.0.140+fabric
- Fabric API - 0.110.0+1.21.1
- Fabric Language Kotlin - 1.13.0+kotlin.2.1.0
- Fzzy Config - 0.5.8+1.21
- Mana Attributes - 2.4.0
- Player Attribute Screen - 1.0.0
- Resource Bar API - 2.4.1
- Runes - 1.0.3+1.21.1
- Spell Engine - 1.1.2+1.21.1
- Spell Engine Extension -  2.2.0
- Spell Power Attributes - 1.0.5+1.21.1
- Structure Pool API - 1.1.3+1.21.1
- Trinkets - 3.10.0
- Wizards (RPG Series) - 2.1.0+1.21.1
- playerAnimator - 2.0.0-alpha1+1.21-fabric

All Configs are default.

**Reproduction**

1. Launch Client
2. Create new World
3. Mana Bar does not appear
4. Open Character Attribute Screen
5. Max Mana is set to 0.0
6. Create Tome of Fire
7. Casting Spells still costs runes
8. I can cast spells as long as I have runes, there is no limit.

Please let me know if I can provide anymore info or tests for you or if Ive simply overlooked something.
Thanks!

![Mana_Attributes_No_Mana_Bar_1](https://github.com/user-attachments/assets/653e7e36-2804-424e-98c7-60f2dcad75ab)
![Mana_Attributes_No_Mana_Bar_2](https://github.com/user-attachments/assets/4c9955f2-4884-4ae4-8a1f-74b5b168eacf)
![Mana_Attributes_Player_attribute_screen](https://github.com/user-attachments/assets/f5bc0cf5-1dad-42b1-8cc5-e5599da2101d)

**Comment by TheRedBrain** [comment]
Hi!

Thanks for the detailed information!

I see Mana Attributes more as a library. not as a content mod, which is why I set the default max value to 0.

Like all entity attributes max mana can be modified by commands.

Do you think it should be greater 0 by default?

All additions from Spell Engine Extension have a default value which does not impact gameplay. All features have to explicitly "enabled". For spells this is done via a data pack.
This is the reason why your spells still cost runes.

**Comment by Lemenok** [comment]
Gotcha!

Thank you for the information. I was considering this as a bug since I was working with your Stamina Attributes mod and it has built in defaults for the actions. So I assumed that the Mana Attributes functioned the same way.

Do you have a default datapack that you work with to test the mana attributes? Otherwise I can just create my own but it would give me a head start.

Thank you so much for your work on these mods by the way!

**Comment by TheRedBrain** [comment]
Stamina Attributes has build in integration because actions like jumping or sprinting are one of the main stamina consuming gameplay elements.

Mana doesn't have anything similar (in the vanilla game), which is why no defaults are implemented.

I currently have no data pack like that.

Thank you for giving feedback!

**Comment by Lemenok** [comment]
Ok, Thanks for your clarification on things! I'll go ahead and close this.
